sudo: required
language: generic

services:
  - docker

before_install:
  -   - docker build -t konsloiz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true konsloiz/react-test npm test

after_success:
  - docker build -t konsloiz/multi-docker-client ./client
  - docker build -t konsloiz/multi-docker-nginx ./nginx
  - docker build -t konsloiz/multi-docker-server ./server
  - docker build -t konsloiz/multi-docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images and push them to docker hub
  - docker push konsloiz/multi-docker-client
  - docker push konsloiz/multi-docker-nginx
  - docker push konsloiz/multi-docker-server
  - docker push konsloiz/multi-docker-worker